### ISSUE TITLE
Use ripples within dynamically generated elements

### ISSUE THREAD

**Issue by ojvribeiro** [matthias-vogt/legitRipple.js#14]
Hi! I'm wondering how can I use the library properly on dynamically generated elements, since my attempts failed.

**Comment by juni-vogt** [comment]
Hey :) dynamically generated elements should work just fine
http://jsbin.com/lejoyizuja/edit?html,css,js,output
Where did your attempts fail?

**Comment by ojvribeiro** [comment]
Hey! You're right, it is working fine on JS Bin.

I'm using cellphone now, but soon I come back with a fiddle. :)

**Comment by ojvribeiro** [comment]
I just realized that I dind't call `$(selector).ripple()` after the element creation. ~facepalm

Thanks!

**Comment by juni-vogt** [comment]
You're welcome!
