### ISSUE TITLE
How to use it with Angular JS?

### ISSUE THREAD

**Issue by carlo-fontanos** [matthias-vogt/legitRipple.js#20]
Hi,

I am currently working on a single page app angular project and I've been successful in getting the ripple to work on the home page. but when I navigate to another route, for example: about page, then I click on a button that has a ripple on it - the ripple does not seem to work.

I think the problem is that legitRipple was not able to attach the event to the button found in the about page because it wasn't on the DOM yet when it got initialized.

**Comment by juni-vogt** [comment]
Yeah I think you're on the right track. I am not familiar with angular but I'm sure you will find some callback or event handler that is executed on navigation, i.e. after new dom elements are added that you want to have ripples on. So just initialize the plugin each time the DOM changes this way.
