### ISSUE TITLE
Bug? IE 11 "Object doesn't support property or method 'startsWith'"

### ISSUE THREAD

**Issue by jwstemper** [matthias-vogt/legitRipple.js#8]
Running the basic example & even the demo page in IE 11 throws the error "Object doesn't support property or method 'startsWith'" when the library attempts to load.
This even happens on the demo page (https://matthias-vogt.github.io/legitRipple.js/)

The problem seems to be in the "isTouchEvent" function on line 34.

It looks like this library requires ECMAScript 6+? IE 11 doesn't use this at this time.

**Comment by juni-vogt** [comment]
Thanks for reporting, I didn't realize that startsWith is an ES6 feature.
